#!/usr/bin/env python3
"""Turn an rdmsr_bench CSV into the shared header for future VMX tests."""
import argparse
import csv
from pathlib import Path
import statistics


def calibration(path):
    with path.open(encoding="utf-8") as source:
        metadata = source.readline().strip()
        if not metadata.startswith("# "):
            raise ValueError("missing rdmsr_bench metadata line")
        fields = dict(item.split("=", 1) for item in metadata[2:].split())
        if fields.get("units") != "tsc_ticks":
            raise ValueError("expected units=tsc_ticks")
        msr = int(fields["msr"], 0)
        cpu = int(fields["cpu"])
        if msr not in (0xe8, 0xe7, 0x10) or cpu < 0:
            raise ValueError("invalid MSR or CPU metadata")
        reader = csv.DictReader(source)
        if reader.fieldnames != ["sample", "empty_ticks", "rdmsr_ticks"]:
            raise ValueError("expected sample,empty_ticks,rdmsr_ticks columns")
        empty, measured = [], []
        for index, row in enumerate(reader):
            if None in row or int(row["sample"]) != index:
                raise ValueError("malformed row or nonsequential sample index")
            baseline, elapsed = int(row["empty_ticks"]), int(row["rdmsr_ticks"])
            if baseline < 0 or elapsed < 0:
                raise ValueError("tick counts must be nonnegative")
            empty.append(baseline)
            measured.append(elapsed)
        if not empty or len(empty) != int(fields["samples"]):
            raise ValueError("empty CSV or sample count does not match metadata")
    baseline = statistics.median(empty)
    overhead = statistics.median(measured) - baseline
    if overhead <= 0:
        raise ValueError("RDMSR overhead must be positive; repeat the calibration")
    return cpu, msr, len(empty), baseline, overhead


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path)
    args = parser.parse_args()
    try:
        cpu, msr, count, baseline, overhead = calibration(args.csv)
    except (OSError, ValueError, KeyError, TypeError, csv.Error) as error:
        parser.exit(1, f"Calibration failed: {error}\n")
    output = Path(__file__).resolve().parent / "build" / "vmx_calibration.h"
    output.parent.mkdir(exist_ok=True)
    output.write_text(
        "/* Generated by calibrate.py. Recalibrate on each test machine. */\n"
        "#ifndef VMX_CALIBRATION_H\n#define VMX_CALIBRATION_H\n"
        f"#define CALIBRATION_CPU {cpu}u\n"
        f"#define CALIBRATION_MSR 0x{msr:x}u\n"
        f"#define CALIBRATION_SAMPLES {count}u\n"
        f"#define EMPTY_BRACKET_TSC_TICKS {float(baseline)!r}\n"
        f"#define RDMSR_OVERHEAD_TSC_TICKS {float(overhead)!r}\n"
        "/* Estimate only: not APERF ticks, core cycles, or a universal\n"
        " * correction to subtract from future VMX measurements. */\n"
        "#endif\n", encoding="utf-8")
    print(f"RDMSR overhead: {overhead:g} TSC ticks (MSR 0x{msr:x}, CPU {cpu})")
    print(f"Shared calibration: {output}")


if __name__ == "__main__":
    main()
